"""Type stubs for okta.client.Client (v3).

The v3 SDK annotates methods as returning plain objects (e.g. ``List[User]``)
but the actual runtime return value is always a 3-tuple
``(data | None, ApiResponse | None, error | None)``.
These stubs correct that so type-checkers understand our unpacking pattern.
"""

from typing import Any

from okta.api_response import ApiResponse
from okta.models.application import Application
from okta.models.device_assurance import DeviceAssurance
from okta.models.group import Group
from okta.models.group_rule import GroupRule
from okta.models.log_event import LogEvent
from okta.models.policy import Policy
from okta.models.user import User

OktaError = Any  # SDK uses custom error objects

class Client:
    def __init__(self, user_config: dict = ...) -> None: ...

    # ── Users ──────────────────────────────────────────────────────────────
    async def list_users(self, **kwargs: Any) -> tuple[list[User] | None, ApiResponse | None, OktaError]: ...
    async def get_user(self, user_id: str, **kwargs: Any) -> tuple[User | None, ApiResponse | None, OktaError]: ...
    async def create_user(self, body: Any, **kwargs: Any) -> tuple[User | None, ApiResponse | None, OktaError]: ...
    async def update_user(
        self, user_id: str, body: Any, **kwargs: Any
    ) -> tuple[User | None, ApiResponse | None, OktaError]: ...
    async def deactivate_user(self, user_id: str, **kwargs: Any) -> tuple[None, ApiResponse | None, OktaError]: ...
    async def delete_user(self, user_id: str, **kwargs: Any) -> tuple[None, ApiResponse | None, OktaError]: ...
    async def list_user_groups(
        self, user_id: str, **kwargs: Any
    ) -> tuple[list[Group] | None, ApiResponse | None, OktaError]: ...

    # ── Applications ───────────────────────────────────────────────────────
    async def list_applications(
        self, **kwargs: Any
    ) -> tuple[list[Application] | None, ApiResponse | None, OktaError]: ...
    async def get_application(
        self, app_id: str, **kwargs: Any
    ) -> tuple[Application | None, ApiResponse | None, OktaError]: ...
    async def create_application(
        self, body: Any, **kwargs: Any
    ) -> tuple[Application | None, ApiResponse | None, OktaError]: ...
    async def replace_application(
        self, app_id: str, body: Any, **kwargs: Any
    ) -> tuple[Application | None, ApiResponse | None, OktaError]: ...
    async def delete_application(self, app_id: str, **kwargs: Any) -> tuple[None, ApiResponse | None, OktaError]: ...
    async def activate_application(self, app_id: str, **kwargs: Any) -> tuple[None, ApiResponse | None, OktaError]: ...
    async def deactivate_application(
        self, app_id: str, **kwargs: Any
    ) -> tuple[None, ApiResponse | None, OktaError]: ...

    # ── Groups ─────────────────────────────────────────────────────────────
    async def list_groups(self, **kwargs: Any) -> tuple[list[Group] | None, ApiResponse | None, OktaError]: ...
    async def get_group(self, group_id: str, **kwargs: Any) -> tuple[Group | None, ApiResponse | None, OktaError]: ...
    async def add_group(self, body: Any, **kwargs: Any) -> tuple[Group | None, ApiResponse | None, OktaError]: ...
    async def replace_group(
        self, group_id: str, body: Any, **kwargs: Any
    ) -> tuple[Group | None, ApiResponse | None, OktaError]: ...
    async def delete_group(self, group_id: str, **kwargs: Any) -> tuple[None, ApiResponse | None, OktaError]: ...
    async def list_group_users(
        self, group_id: str, **kwargs: Any
    ) -> tuple[list[User] | None, ApiResponse | None, OktaError]: ...
    async def list_assigned_applications_for_group(
        self, group_id: str, **kwargs: Any
    ) -> tuple[list[Application] | None, ApiResponse | None, OktaError]: ...
    async def assign_user_to_group(
        self, group_id: str, user_id: str, **kwargs: Any
    ) -> tuple[None, ApiResponse | None, OktaError]: ...
    async def unassign_user_from_group(
        self, group_id: str, user_id: str, **kwargs: Any
    ) -> tuple[None, ApiResponse | None, OktaError]: ...

    # ── Group Rules ────────────────────────────────────────────────────────
    async def list_group_rules(
        self, **kwargs: Any
    ) -> tuple[list[GroupRule] | None, ApiResponse | None, OktaError]: ...
    async def get_group_rule(
        self, rule_id: str, **kwargs: Any
    ) -> tuple[GroupRule | None, ApiResponse | None, OktaError]: ...
    async def activate_group_rule(self, rule_id: str, **kwargs: Any) -> tuple[None, ApiResponse | None, OktaError]: ...

    # ── Policies ───────────────────────────────────────────────────────────
    async def list_policies(self, **kwargs: Any) -> tuple[list[Policy] | None, ApiResponse | None, OktaError]: ...
    async def get_policy(
        self, policy_id: str, **kwargs: Any
    ) -> tuple[Policy | None, ApiResponse | None, OktaError]: ...
    async def create_policy(self, body: Any, **kwargs: Any) -> tuple[Policy | None, ApiResponse | None, OktaError]: ...
    async def replace_policy(
        self, policy_id: str, body: Any, **kwargs: Any
    ) -> tuple[Policy | None, ApiResponse | None, OktaError]: ...
    async def delete_policy(self, policy_id: str, **kwargs: Any) -> tuple[None, ApiResponse | None, OktaError]: ...
    async def activate_policy(self, policy_id: str, **kwargs: Any) -> tuple[None, ApiResponse | None, OktaError]: ...
    async def deactivate_policy(self, policy_id: str, **kwargs: Any) -> tuple[None, ApiResponse | None, OktaError]: ...
    async def list_policy_rules(
        self, policy_id: str, **kwargs: Any
    ) -> tuple[list[Any] | None, ApiResponse | None, OktaError]: ...
    async def get_policy_rule(
        self, policy_id: str, rule_id: str, **kwargs: Any
    ) -> tuple[Any | None, ApiResponse | None, OktaError]: ...
    async def create_policy_rule(
        self, policy_id: str, body: Any, **kwargs: Any
    ) -> tuple[Any | None, ApiResponse | None, OktaError]: ...
    async def replace_policy_rule(
        self, policy_id: str, rule_id: str, body: Any, **kwargs: Any
    ) -> tuple[Any | None, ApiResponse | None, OktaError]: ...
    async def delete_policy_rule(
        self, policy_id: str, rule_id: str, **kwargs: Any
    ) -> tuple[None, ApiResponse | None, OktaError]: ...
    async def activate_policy_rule(
        self, policy_id: str, rule_id: str, **kwargs: Any
    ) -> tuple[None, ApiResponse | None, OktaError]: ...
    async def deactivate_policy_rule(
        self, policy_id: str, rule_id: str, **kwargs: Any
    ) -> tuple[None, ApiResponse | None, OktaError]: ...

    # ── Device Assurance ───────────────────────────────────────────────────
    async def list_device_assurance_policies(
        self, **kwargs: Any
    ) -> tuple[list[DeviceAssurance] | None, ApiResponse | None, OktaError]: ...
    async def get_device_assurance_policy(
        self, device_assurance_id: str, **kwargs: Any
    ) -> tuple[DeviceAssurance | None, ApiResponse | None, OktaError]: ...
    async def create_device_assurance_policy(
        self, device_assurance: Any, **kwargs: Any
    ) -> tuple[DeviceAssurance | None, ApiResponse | None, OktaError]: ...
    async def replace_device_assurance_policy(
        self, device_assurance_id: str, device_assurance: Any, **kwargs: Any
    ) -> tuple[DeviceAssurance | None, ApiResponse | None, OktaError]: ...
    async def delete_device_assurance_policy(
        self, device_assurance_id: str, **kwargs: Any
    ) -> tuple[None, ApiResponse | None, OktaError]: ...

    # ── System Logs ────────────────────────────────────────────────────────
    async def list_log_events(self, **kwargs: Any) -> tuple[list[LogEvent] | None, ApiResponse | None, OktaError]: ...
